// Which app a dictation went to, as a coarse label for anonymous usage counts.
// Only apps on this closed list are named; everything else is "other", so a rare or in-house
// program never leaves the machine. Keys are lower-case: process names without ".exe" (executable
// names on Linux), and macOS app bundle names without ".app" (not localized, unlike the Dock name).

const APPS: Record<string, string> = {
  // Coding agents and editors
  "t3 code": "t3code", // channel builds are "T3 Code (Alpha)", "T3 Code (Nightly)": see appLabel
  claude: "claude",
  codex: "codex",
  chatgpt: "chatgpt",
  code: "vscode",
  "code - insiders": "vscode",
  cursor: "cursor",
  windsurf: "windsurf",
  zed: "zed",
  devenv: "visualstudio",
  idea64: "jetbrains",
  pycharm64: "jetbrains",
  webstorm64: "jetbrains",
  rider64: "jetbrains",
  clion64: "jetbrains",
  goland64: "jetbrains",
  datagrip64: "jetbrains",
  "visual studio code": "vscode",
  xcode: "xcode",
  "intellij idea": "jetbrains",
  "intellij idea ce": "jetbrains",
  pycharm: "jetbrains",
  "pycharm ce": "jetbrains",
  webstorm: "jetbrains",
  rider: "jetbrains",
  clion: "jetbrains",
  goland: "jetbrains",
  datagrip: "jetbrains",
  // Terminals
  windowsterminal: "terminal",
  cmd: "terminal",
  powershell: "terminal",
  pwsh: "terminal",
  conhost: "terminal",
  "wezterm-gui": "terminal",
  alacritty: "terminal",
  mintty: "terminal",
  "gnome-terminal-server": "terminal",
  kgx: "terminal",
  ptyxis: "terminal",
  konsole: "terminal",
  kitty: "terminal",
  foot: "terminal",
  ghostty: "terminal",
  "xfce4-terminal": "terminal",
  tilix: "terminal",
  xterm: "terminal",
  terminal: "terminal",
  iterm: "terminal",
  warp: "terminal",
  wezterm: "terminal",
  // Browsers
  chrome: "browser",
  msedge: "browser",
  firefox: "browser",
  "firefox-bin": "browser",
  chromium: "browser",
  brave: "browser",
  opera: "browser",
  vivaldi: "browser",
  arc: "browser",
  browser: "browser", // Yandex Browser
  "google chrome": "browser",
  safari: "browser",
  "microsoft edge": "browser",
  "brave browser": "browser",
  yandex: "browser",
  // Messengers and calls
  telegram: "telegram",
  ayugram: "telegram",
  slack: "slack",
  discord: "discord",
  whatsapp: "whatsapp",
  "ms-teams": "teams",
  teams: "teams",
  zoom: "zoom",
  "zoom.us": "zoom",
  "microsoft teams": "teams",
  // Documents and notes
  winword: "word",
  excel: "excel",
  powerpnt: "powerpoint",
  outlook: "outlook",
  olk: "outlook",
  onenote: "onenote",
  "microsoft word": "word",
  "microsoft excel": "excel",
  "microsoft powerpoint": "powerpoint",
  "microsoft outlook": "outlook",
  "microsoft onenote": "onenote",
  textedit: "notepad",
  notes: "notepad",
  notion: "notion",
  obsidian: "obsidian",
  notepad: "notepad",
  "notepad++": "notepad",
  explorer: "explorer",
  finder: "explorer",
};

/** "WindowsTerminal" → "terminal", "Code" → "vscode", an unlisted program → "other". */
export function appLabel(process: string): string {
  const name = process.trim().toLowerCase().replace(/\.exe$/, "").replace(/^t3 code \(.*\)$/, "t3 code");
  return (Object.hasOwn(APPS, name) && APPS[name]) || "other";
}
